index.js, package.json, upload-sourcemaps.js
@brentvatne 
I've tested it with version 0.13 and it works.
I tried to add url as an additional `sentry-cli` parameter and tried using sentry-cli from `node_modules` without success.
Maybe you know why this is not working
Here is the log of the publish process:
```
13:21:49 Running postPublish hook: sentry-expo/upload-sourcemaps
13:21:50 /Users/haza/Desktop/bla/node_modules/sentry-cli-binary/bin/sentry-cli
Error: Process exited with non-zero code: 1
at ChildProcess.child.on (/Users/haza/Desktop/bla/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:885:16)
at Socket.<anonymous> (internal/child_process.js:334:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7) …
```
=> Bump react-native-sentry to 0.13.0

index.js
Added an extra parameter to `config` which enables installing on dev environments. Also added code to swap all Sentry class methods with `noop`s, which fixes #9.
=> Add option to install on dev

package.json, upload-sourcemaps.js
We have an issue where the `@sentry/cli` [package is incompatible](https://github.com/getsentry/sentry-cli/issues/227) with the [standard Docker linux distro Alpine](https://www.reddit.com/r/linux/comments/44e0k2/docker_official_images_are_moving_to_alpine_linux/). In the latest version of this cli package they added an option to use a custom CDN for prebuilt binaries. With this we can work around the incompatibility issue. It might be wise to just update to the latest version to include this ability and other fixes from the repo.
=> Update sentry react native to `0.36.0`

index.js
For calls to captureException that do not generate a proper stacktrace (e.g. called with a string on android, related to issue #4), there are no frames in the stacktrace.
=> check lastFrame

index.js
I've spent some time figuring out why my integration did not work.
I think it's worth documenting the `Sentry.enableInExpoDevelopment=true` attribute because I actually expected this to work in dev too.
Also worth mentioning that if we set Sentry.config = noop like it did, in case someone does hot reload the code and it calls `Sentry.config().install()` again, it produces "can't call install() on undefined" errors due to hot reload. My code fixes this issue as it replaces config fn with a better mock in case Sentry is supposed to be disabled. Also notice it ensures that on hot reload we only log once.
=> Better DX (fix hot reload, better log)

upload-sourcemaps.js
Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.
I try to run 
`
export publish
`
and got the error
`
Running postPublish hook: sentry-expo/upload-sourcemaps
Error uploading sourcemaps to Sentry: API request failed
caused by: sentry reported an error: Invalid token (http status: 401)
`
After checking the log using 
`
SENTRY_LOG_LEVEL=debug
`
it is making a request to https://sentry.io/
`
DEBUG   2019-04-15 11:15:55.558481 +08:00 request POST https://sentry.io/api/0/projects/sentry/projectname/releases/
DEBUG   2019-04-15 11:15:56.354348 +08:00 > Host: sentry.io
`
It is not retrieving the host from process.env.SENTRY_URL
Adding url in postPublish config post to the right host. 
It should also be able to retrieve host from …
=> get config from env

index.d.ts, index.js, package.json, yarn.lock
Tested everything locally and it work 👍 
This is the new API:
```js
import * as Sentry from 'sentry-expo';
Sentry.init({
dsn: 'DSN,
enableInExpoDevelopment: true,
debug: true
});
```
`sentry-expo` now conforms the unified API meaning all function that are in `@sentry/browser` are there.
=> feat: Update Sentry to use @sentry/react-native

index.d.ts
See https://github.com/expo/sentry-expo/pull/58#discussion_r323226432
=> fix(ts): add `enableInExpoDevelopment` to typings

index.js
Since Constants.deviceId is just an alias for Constants.installationId, I thought that tag may as well come from installationId.
=> Modify the deviceId tag to come from installationId instead of deviceId

index.js
closes https://github.com/expo/sentry-expo/issues/93
device name doesn't give much help in terms of bug reporting or troubleshooting, so removing it by default
=> fix: remove devicename

package.json, yarn.lock
Old @sentry/react-native has security issues. that could potentially lead to access to source map in applications at iOS SDK.
Therefore, it is necessary to update to a benign version.
=> sentry/react-native update 1.3.9

upload-sourcemaps.js
Closes #88.
I'm sorry it took so long to open this PR 🤦 .
I went ahead and also added the ability to set [`deploys`](https://docs.sentry.io/workflow/releases/?platform=javascript#create-deploy) too. 
Configuration is as follows with the postPublish `config` attribute.
```json
{
"postPublish": [
{
"file": "sentry-expo/upload-sourcemaps",
"config": {
"setCommits": true,
"deployEnv": "production"
}
}
]
}
```
Or, it can be configured with environment vars (this could be easier than changing up app.json on the fly
```
SENTRY_EXPO_SET_COMMITS=true
SENTRY_EXPO_DEPLOY_ENV=production
```
`setCommits` must be `"true"` or `true` for it to run, and `deployEnv` needs to be any non empty string.
=> feat: ability to set commits and deploys in sourcemaps hook

index.js, upload-sourcemaps.js
this is pretty much a copy of @jtomaszewski's PR
closes https://github.com/expo/sentry-expo/pull/89
closes https://github.com/expo/sentry-expo/pull/111
allows you to set the `release` to whatever you want, not forced into using `revisionId`
You can do this by setting the `SENTRY_RELEASE` env var before publishing, or setting `release` in the postPublish hook config. Note that you should set the `release` field to the same value in your call to `Sentry.init` (probably works best to have this be set to the env variable)
=> feat: set release in config or env var

upload-sourcemaps.js
Adding `--strip-prefix ${projectRoot}` to "remove a path that is build machine specific" as described in [Upload Source Maps](https://docs.sentry.io/cli/releases/#sentry-cli-sourcemaps).
This improves sentry issue display by rendering something like `Error onPress(screens/MyScreen)` instead of `Error onPress(/Users/builder/project/screens/MyScreen)` given `/Users/builder/project/` is the projectRoot.
closes #37
=> fix(upload): strip projectRoot from sourcemaps

README.md, upload-sourcemaps.js
@byCedric pointed out that we could do this and avoid causing a breaking change (now or in the future) for users in their app.json configuration 🙌
=> export uploadSourcemaps hook from root directory

CHANGELOG.md, README.md, dist/hooks/upload-sourcemaps.js, dist/integrations/bare.js, dist/sentry.expo.js, dist/sentry.js, package.json, src/hooks/upload-sourcemaps.ts, src/integrations/bare.ts, src/sentry.expo.ts, src/sentry.ts, yarn.lock
After the [last PR](https://github.com/expo/sentry-expo/pull/129), I realized there was more to do:
- set `release` and `dist` automatically in bare to what sentry expects (less work for user / things to remember)
- change names of android sourcemap files to match Sentry's expected values
- updated the changelog with breaking change for anyone manually uploading sourcemaps
- Fix logic for changing the name of sourcemapped files in bare (this makes the two integrations very similar, we could probably make it one file now)
- fix expected file names in multiple places
This has been tested on android and ios in both bare and managed workflows
=> fix: more bare workflow sourcemap fixes

CHANGELOG.md, dist/integrations/bare.js, dist/integrations/managed.js, src/integrations/bare.ts, src/integrations/managed.ts
Fixes: https://github.com/expo/sentry-expo/issues/138
When you run the app and send a crash the follow error appears on Sentry:
This happen because `manifest` is an empty object.
=> fix: Tags with invalid values

dist/index.d.ts, dist/index.js, dist/sentry.d.ts, dist/sentry.expo.d.ts, dist/sentry.expo.js, dist/sentry.js, dist/sentry.web.d.ts, dist/sentry.web.js, src/index.ts, src/sentry.expo.ts, src/sentry.ts, src/sentry.web.ts
we were exporting the native module even running on web, now we separate the init's completely on native and web
closes https://github.com/expo/sentry-expo/issues/147 and https://github.com/expo/sentry-expo/issues/148
=> fix: fix running on web

dist/sentry.js, src/sentry.ts
It's possible not to set the `enableInExpoDevelopment: true` flag, and then upload/release a build on the appstore and have Sentry be disabled if the build wasn't "published" or "exported" yet.
This only disables Sentry in development if that flag is actually false, and enables Sentry by default in production, unless explictly disabled.
My use case for this one is:
1. Bare Workflow + Self hosting the bundles and uploading them in a post-export hook.
2. I create my app, without having set the `enableInExpoDevelopment` flag.
3. I build/upload it to TestFlight.
4. I do not export any bundles to my self-hosted site yet (since there's no changes against the base bundle in TestFlight), so there is no revisionId/manifest.
5. Sentry is disabled in production b/c `enableInExpoDevelopment` is not …
=> Only disable Sentry in bare workflow in development explicitly.

dist/sentry.js, src/sentry.ts
This was confusing for me, since the `dist` value I actually passed in was not used, and it instead opted to use `manifest.version`. This is fine if I remember to keep both in sync, but also feels weird.
If I'm initializing Sentry with a specific `dist`, shouldn't it use that?
=> Use explicitly passed dist in options

dist/sentry.expo.js, dist/sentry.js, src/sentry.expo.ts, src/sentry.ts
Replace file-directory-bundle stack frame filenames, and also don't replace `[native code]` frames. With this [upstream fix](https://github.com/getsentry/sentry-javascript/pull/3070) applied in `@sentry/browser`, these frames weren't getting replaced which causes source maps to not be applied.
Fixes https://github.com/getsentry/sentry-react-native/issues/1116
=> Replace file directory stack frames and don't replace native code frames

.github/workflows/build.yml
~~This adds a plain CI to avoid issues, like the one we have now with `string | undefined is not assignable to string`.~~
> Edit, looks like it was something local. Maybe I accidentally upgraded some dependencies. Nonetheless, I think it's good to have this.
We can also add this step to check if `dist` is up to date. It's a simple script to detect changes in the `dist` folder and exit with an error if there are. It does not detect additional files though. I've used this one in [`expo/expo-github-action`](https://github.com/expo/expo-github-action/blob/master/.circleci/config.yml#L17).
```
- name: Build up-to-date
run: git diff --stat --exit-code dist
```
An alternative to _detect_ deleted files would be to remove the `dist` folder before building. And then running the check listed above. …
=> chore: add simple build ci to test package

src/sentry.ts
While running `yarn start`, I always see the console log:
```
[sentry-expo] Disabled Sentry in development. Note you can set Sentry.init({ enableInExpoDevelopment: true });
```
I think this log should not be shown if I already set `enableInExpoDevelopment` (to `true` or `false`).
I have this code in my project:
```
import * as Sentry from 'sentry-expo';
import Constants from 'expo-constants';
Sentry.init({
dsn: 'xxxx',
enableInExpoDevelopment: false,
release: Constants.manifest.revisionId,
});
```
As you can see, I'm already aware of the existance of `enableInExpoDevelopment`, so, the warning is unnecessary.
Not sure if `typeof xxx...` is the way to go here. I don't have context about TypeScript. Let me know if there is a cleaner way, I can change it.
=> Hide log if option is already known

package.json, yarn.lock
Since `@sentry/react-native` forces `6.7.1` (no semver range), this module should not force duplication on consumers
=> fix: dedupe sentry dependencies

plugin/src/withSentryIOS.ts
There should not be a line break between sentry-cli call and the package script. See https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#bundle-react-native-code-and-images. Note the backslash in the instructions that escapes the line break. Here we can just use a space instead and keep everything on the same line.
=> Fix build phase script on iOS

README.md
I made some changes to the [Using Sentry](https://docs.expo.dev/guides/using-sentry/) docs page and realized that we have the same content here. It's better to maintain a single source of truth, and I think (at least for now) our documentation is better suited for the job.
=> [readme] Link out to the documentation rather than repeating it

CHANGELOG.md
A couple of code-blocks were not properly terminated
Changelog formatting is broken for older versions
Terminated some code blocks properly
I just previewed the markdown changes
=> Fix formatting

CHANGELOG.md, package.json, yarn.lock
Without this, the following warnings are printed when running `yarn` in this repo
```
warning " > expo-updates@0.14.3" has unmet peer dependency "expo@*".
warning "expo-updates > expo-updates-interface@0.7.0" has unmet peer dependency "expo@*".
```
Just updated `package.json` and ran `yarn`
🤷
=> fix: add peer dependency on `expo`

CHANGELOG.md, src/integrations/bare.ts
Hi there, I am experiencing an issue in our app where instead of an expected exception being logged in the redbox in development, the following error is logged instead:
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'error.stack.replace')
```
The stack trace in the redbox lead me to the function in question. By adding a `console.error` log in the file `node_modules/sentry-expo/build/integrations/bare.js` I verified that an exception was thrown by my app which has an undefined `error.stack` property.
This happened to be an `AssertionError`, thrown by `assert.equal` from [assert](https://npm.im/assert). I'm sure it's possible to reproduce this in another project using this code:
```ts
import assert from 'assert'
assert.equal(1, 2, 'This …
```
=> fix: stop assuming that error.stack is defined

CHANGELOG.md, package.json, yarn.lock
This is to address this issue on Expo SDK 47
https://github.com/getsentry/sentry-react-native/issues/2676
Bump the version of the library @sentry/react-native in the package.json
Just run the app and you will see this annoying warning error
=> Bump sentry react native version

CHANGELOG.md, plugin/build/withSentryAndroid.d.ts, plugin/build/withSentryAndroid.js, plugin/src/__tests__/modifyAppBuildGradle-test.ts, plugin/src/withSentryAndroid.ts
The app/build.gradle template changed in RN 0.71, breaking the sentry script injection because the old injection point doesn't exist anymore. 
This change opts for a safer injection point, that is backwards compatible, and matches the sentry-wizard implementation.
Local testing, the result is as expected, in app/build.gradle:
```gradle
apply from: new File(["node", "--print", "require.resolve('@sentry/react-native/package.json')"].execute().text.trim(), "../sentry.gradle")
android {
```
=> [plugin] update android script injection logic

CHANGELOG.md, plugin/build/withSentry.js, plugin/src/__tests__/getSentryProperties-test.ts, plugin/src/withSentry.ts
See #321 
Added a warning whenever you configure `authToken` through the post-publish hook.
- `$ yarn create expo-app ./test-authtoken`
- `$ cd ./test-authtoken`
- `$ yarn expo install sentry-expo`
- Configure `app.json` with the post-publish token, including `authToken`
- `$ yarn expo prebuild`
- Warning should be visible
=> fix: discourage `authToken` usage and link to updated docs

CHANGELOG.md, plugin/build/withSentryAndroid.js, plugin/src/withSentryAndroid.ts
Thanks to @anirudhsama and @maximgeerinck for the original [workaround](https://github.com/expo/sentry-expo/issues/292#issuecomment-1544211475).
Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.
closes: https://github.com/expo/sentry-expo/issues/342
How did you build this feature or fix this bug and why?
This is already fixed in `sentry-react-native`. But until released and upgraded here, this PR will work for all the versions.
https://github.com/getsentry/sentry-react-native/pull/3092
Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your …
=> fix: Dynamically resolve `collectModulesScript` script path to support monorepos

CHANGELOG.md, package.json, yarn.lock
Customers having this issue have to manually upgrade the cli at the moment.
- https://github.com/expo/sentry-expo/issues/364
- supersedes https://github.com/expo/sentry-expo/pull/367 and https://github.com/expo/sentry-expo/pull/358
=> Upgrade to sentry-react-native 5.10.0 and sentry-javascript 7.69.0

README.md
With the release of SDK 50 `sentry-expo` was deprecated in favor of `@sentry/react-native`. But Sentry customers might still find the `sentry-expo` repository on the internet. This deprecation notice will help them to use the up-to-date SDK.
=> Add deprecation notice and migration guide
